apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: idlblhxxj-go 
  janus-idp.io/tekton: idlblhxxj-go
  backstage.io/kubernetes-id: idlblhxxj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: idlblhxxj-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  